Posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('',views.show_posts_all,name='index'),
    path('add_post/',views.add_new_post,name='add_new_post'),
]

Register_and_login/urls.py
from django.urls import path
from . import views

app_name = 'register_and_login'
urlpatterns = [
    path('',views.index,name='index'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path ,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Posts/',include('Posts.urls')),
    path('accounts/',include('Register_and_login.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

Posts/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

class Post(models.Model):
    title = models.CharField( max_length=50)
    body = models.TextField(max_length=500)
    create_date = models.DateField(auto_now_add=True)
    last_update_date = models.DateField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField(max_length=250)
    create_date = models.DateField(auto_now_add=True)
    author =models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.body

Register_and_login/models.py
from django.db import models

# Create your models here.

Register_and_login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

Posts/views.py
from django.shortcuts import render
from .models import Post,Comment
from django import forms
from django.utils import timezone
# Create your views here.

class PostADDForm(forms.Form):
    title = forms.CharField(max_length=50)
    body = forms.CharField(max_length=500)

############################################################

def show_posts_all(request):
    post =Post.objects.all()
    context = {
        'posts':post,
    }
    return render(request,'Posts/index.html',context)

def add_new_post(request):
    form = PostADDForm()
    if request.method == 'POST':
        form = PostADDForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            body = form.cleaned_data['body']
            author = request.user
            create_date = timezone.now()
            last_update_date = timezone.now()

            # Utwórz nowy post i zapisz go do bazy danych
            Post.objects.create(
                title=title,
                body=body,
                author=author,
                create_date=create_date,
                last_update_date=last_update_date
            )

            # Przekieruj użytkownika na stronę z postami po dodaniu nowego postu
            return render(request, 'Posts/index.html', {'posts': Post.objects.all()})
    
    # Jeśli żądanie to GET, wyświetl formularz
    return render(request, 'Posts/add_post.html', {'form': form})

Register_and_login/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'Register_and_login/index.html',{})

Posts/templates/Posts/add_post.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html>
<head>
    {% tailwind_css %}
    <title>Blog</title>
</head>
<body>
    <!-- Formularz dodawania nowego postu -->
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
            <br>
        {% endfor %}
        <input type="submit" value="Dodaj">
    </form>
</body>
</html>

Posts/templates/Posts/index.html
<!-- FILEPATH: /home/kuba/django/myblog/Posts/templates/Posts/index.html -->

{% load static tailwind_tags %}

<!DOCTYPE html>
<html>
<head>
    {% tailwind_css %}
    <title>Blog</title>
</head>
<body>
    <!-- Sekcja wyświetlająca posty -->
    <div>
        <h2>Posty</h2>
        {% for post in posts%}
          <h3>{{post.title}}</h3>
          <p>{{post.body}}</p>
          <p>{{post.create_date}}</p>
          <p> {{post.author}}</p>
          {% endfor %}
    </div>

    <!-- Formularz dodawania nowego postu -->
    <a href="{% url 'posts:add_new_post' %}">Dodaj nowy post</a>
</body>
</html>

Posts/templates/Posts/register.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>My Site</title>
</head>
<body>
    <h1 class="text-4xl">Hello World</h1>
</body>
</html>

Register_and_login/templates/Register_and_login/index.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>My Register</title>
</head>
<body>
    <h1 class="text-4xl">Lest's Register some bestard ;DD</h1>
    {% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" class="form-group">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock %}

</body>
</html>

theme/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>